from django.urls import path
from . import views
urlpatterns = [
    path('', views.home,name='schemes-home'),
    path('businessloans/',views.businessloans,name='schemes-businessloans'),
    path('health/',views.health,name='schemes-health'),
    path('pension/',views.pension,name='schemes-pension'),
    path('housing/',views.housing,name='schemes-housing'),
    path('training_and_employment/',views.training_and_employment,name='schemes-training_and_employment'),
    path('insurance/', views.insurance, name='schemes-insurance'),
    path('financial_accounts/', views.financial_accounts, name='schemes-finanacial_accounts'),
    path('education/', views.education, name='schemes-education'),
    path('pension/PMVVY/', views.PMVVY, name='schemes-PMVVY'),
    path('pension/APY/', views.APY, name='schemes-APY'),
    path('businessloans/SUILS/', views.SUILS, name='schemes-SUILS'),
    path('businessloans/SCM/', views.SCM, name='schemes-SCM'),
    path('businessloans/PMMY/', views.PMMY, name='schemes-PMMY'),
    path('health/RSBMY/', views.RSBMY, name='schemes-RSBMY'),
    path('health/PMSMY/', views.PMSMY, name='schemes-PMSMY'),
    path('health/PMJAYA/', views.PMJAYA, name='schemes-PMJAYA'),
    path('financial_accounts/PMJDY/', views.PMJDY, name='schemes-PMJDY'),
    path('financial_accounts/PMSSY/', views.PMSSY, name='schemes-PMSSY'),
    path('housing/AAY/', views.AAY, name='schemes-AAY'),
    path('housing/PMUY/', views.PMUY, name='schemes-PMUY'),
    path('housing/PMAY/', views.PMAY, name='schemes-PMAY'),
    path('housing/PMSY/', views.PMSY, name='schemes-PMSY'),
    path('housing/Ujala/', views.Ujala, name='schemes-Ujala'),
    path('training_and_employment/NREGA/', views.NREGA, name='schemes-NREGA'),
    path('training_and_employment/PMKVY/', views.PMKVY, name='schemes-PMKVY'),
    path('insurance/PMFBY/', views.PMFBY, name='schemes-PMFBY'),
    path('insurance/PMSBY/', views.PMSBY, name='schemes-PMSBY'),
    path('insurance/PMJJBY/', views.PMJJBY, name='schemes-PMJJBY'),
    path('education/PMSS/', views.PMSS, name='schemes-PMSS'),
    path('education/PMVLK/', views.PMVLK, name='schemes-PMVLK'),
    path('eligible/', views.eligible, name='schemes-eligible'),
    path('noteligible/', views.noteligible, name='schemes-noteligible'),
]