# Generated by Django 2.1.2 on 2018-10-20 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0002_scheme_apply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheme',
            name='apply',
        ),
    ]
