# Generated by Django 2.1.2 on 2018-11-06 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0004_sch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sch',
        ),
    ]
