# Generated by Django 2.1.2 on 2018-11-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0006_sc'),
    ]

    operations = [
        migrations.AddField(
            model_name='sc',
            name='e',
            field=models.TextField(default='hey'),
        ),
    ]
