# Generated by Django 2.1.2 on 2018-11-06 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0007_sc_e'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sc',
        ),
    ]
