# Generated by Django 2.1.2 on 2018-11-07 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0009_scheme_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='scheme_details',
        ),
    ]
