# Generated by Django 2.1.2 on 2018-11-07 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0011_scheme_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='scheme',
        ),
    ]
